# Generated by Django 4.2.10 on 2025-06-10 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(db_index=True, unique=True)),
                ("held_at", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("minutes_url", models.URLField(blank=True)),
                (
                    "minutes_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="meeting_minutes/",
                        verbose_name="صورتجلسه امضا شده",
                    ),
                ),
                (
                    "other_invitees",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="سایر مدعوین"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meetings_attended",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="حاضرین جلسه",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resolution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("clause", models.CharField(max_length=10, verbose_name="بند")),
                ("subclause", models.CharField(max_length=10, verbose_name="زیربند")),
                ("description", models.TextField(verbose_name="شرح مصوبه")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("operational", "عملیاتی"),
                            ("informational", "اطلاع\u200cرسانی"),
                        ],
                        max_length=20,
                        verbose_name="نوع مصوبه",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="درصد پیشرفت"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("cancelled", "منتفی"),
                            ("notified", "در حال ابلاغ"),
                            ("in_progress", "در حال اجرا"),
                            ("completed", "تکمیل شده"),
                            ("returned_to_secretary", "برگشت به دبیر"),
                        ],
                        default="notified",
                        max_length=30,
                        verbose_name="وضعیت مصوبه",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="مهلت انجام"),
                ),
                (
                    "can_edit",
                    models.BooleanField(
                        default=False, verbose_name="قابل ویرایش توسط دبیر"
                    ),
                ),
                (
                    "coworkers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coworked_resolutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="همکاران",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_resolutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "executor_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_resolutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="واحد مجری",
                    ),
                ),
                (
                    "inform_units",
                    models.ManyToManyField(
                        blank=True,
                        related_name="informed_resolutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="واحدهای اطلاع\u200cرسانی",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="core.meeting",
                        verbose_name="شماره جلسه",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="participated_resolutions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="شرکت\u200cکنندگان",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResolutionAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("return_to_secretary", "برگشت به دبیر"),
                            ("return", "برگشت"),
                            ("accept", "قبول"),
                            ("edit", "ویرایش"),
                            ("referral", "ارجاع"),
                            ("progress_update", "به\u200cروزرسانی پیشرفت"),
                            ("status_change", "تغییر وضعیت"),
                            ("add_participant", "اضافه کردن شرکت\u200cکننده"),
                            ("remove_participant", "حذف شرکت\u200cکننده"),
                        ],
                        max_length=30,
                        verbose_name="نوع اکشن",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="داده\u200cهای اکشن"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResolutionComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("message", "پیام"),
                            ("action", "اکشن"),
                            ("progress_update", "بروزرسانی پیشرفت"),
                            ("return", "برگشت"),
                            ("referral", "ارجاع"),
                        ],
                        default="message",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("action_data", models.JSONField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mentions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="mentioned_in_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.resolutionaction",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.resolutioncomment",
                    ),
                ),
                (
                    "resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.resolution",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("deputy", "معاون"),
                            ("manager", "مدیر"),
                            ("head", "رئیس اداره"),
                            ("employee", "کارمند"),
                            ("secretary", "دبیر"),
                            ("auditor", "ناظر"),
                            ("ceo", "مدیرعامل"),
                            ("board", "هیئت مدیره"),
                        ],
                        default="employee",
                        max_length=20,
                        verbose_name="سمت",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="واحد/اداره"
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سرپرست",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResolutionCommentAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="comment_attachments/%Y/%m/",
                        verbose_name="فایل پیوست",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="نام اصلی فایل"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="اندازه فایل (بایت)"),
                ),
                (
                    "file_type",
                    models.CharField(max_length=100, verbose_name="نوع فایل"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان آپلود"),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.resolutioncomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل پیوست کامنت",
                "verbose_name_plural": "فایل\u200cهای پیوست کامنت\u200cها",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="resolutionaction",
            name="related_comment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_reference",
                to="core.resolutioncomment",
            ),
        ),
        migrations.AddField(
            model_name="resolutionaction",
            name="resolution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="core.resolution",
                verbose_name="مصوبه",
            ),
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referred_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="core.resolution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.resolution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="core.resolution",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResolutionView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.resolution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolution_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "resolution")},
            },
        ),
    ]
